apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  namespace: mesh-demo
  labels:
    app: frontend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend
        version: v2
    spec:
      serviceAccountName: frontend
      containers:
        - name: frontend
          image: hashicorp/http-echo:1.0
          args:
            - "-text=FRONTEND v2"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"